<?php

/**
 * Implements hook_theme().
 */
function dermau_core_theme($existing, $type, $theme, $path) {
  return [
    'dermau_slider_block' => [
      'variables' => [
        'sliders' => [],
      ],
      'template' => 'dermau-slider-block',
    ],
    'dermau_stats_block' => [
      'variables' => [
        'title_1' => '',
        'title_2' => '',
        'description' => '',
        'items' => [],
      ],
      'template' => 'dermau-stats-block',
    ],
    'dermau_programas_block' => [
      'variables' => [
        'terms' => [],
      ],
      'template' => 'dermau-programas-block',
    ],
  ];
}
