<?php

/**
 * Implements hook_theme().
 */
function dermau_core_theme($existing, $type, $theme, $path) {
  return [
    'dermau_slider_block' => [
      'variables' => [
        'sliders' => [],
      ],
      'template' => 'dermau-slider-block',
    ],
    'dermau_stats_block' => [
      'variables' => [
        'title_1' => '',
        'title_2' => '',
        'description' => '',
        'items' => [],
      ],
      'template' => 'dermau-stats-block',
    ],
    'dermau_programas_block' => [
      'variables' => [
        'terms' => [],
      ],
      'template' => 'dermau-programas-block',
    ],
    'block_convenios' => [
      'variables' => [
        'titulo_parte_1' => NULL,
        'titulo_parte_2' => NULL,
        'descripcion' => NULL,
        'items' => [],
      ],
      'template' => 'block-convenios',
    ],
    'block_testimonios' => [
      'variables' => [
        'titulo_parte_1' => NULL,
        'titulo_parte_2' => NULL,
        'texto_boton' => NULL,
        'texto_boton_highlight' => NULL,
        'url_boton' => NULL,
        'items' => [],
      ],
      'template' => 'block-testimonios',
    ],
    'block_faq' => [
      'variables' => [
        'titulo_parte_1' => NULL,
        'titulo_parte_2' => NULL,
        'descripcion' => NULL,
        'categorias' => [],
      ],
      'template' => 'block-faq',
    ],
  ];
}

use Drupal\node\Entity\Node;

function dermau_core_preprocess_node(&$variables) {

  if (empty($variables['node'])) {
    return;
  }

  $node = $variables['node'];

  if ($node->bundle() !== 'programa') {
    return;
  }

  $query = \Drupal::entityQuery('node')
    ->condition('type', 'programa')
    ->condition('status', 1)
    ->condition('nid', $node->id(), '<>')
    ->range(0, 6)
    ->accessCheck(TRUE);

  $nids = $query->execute();

  $variables['otros_programas'] = !empty($nids)
    ? Node::loadMultiple($nids)
    : [];

}

